### ISSUE TITLE
Add VirtualBox Driver

### ISSUE THREAD

**Issue by techhat** [saltstack/salt-cloud#532]
Tagging @UtahDave.

**Comment by dragon788** [comment]
Is this simple for some provisioning commands using VboxManage to create/start/stop/etc VMs?

**Comment by JDiPierro** [comment]
Yeah I think so. You can take a peek at the Vagrant source code to see how it deals with VirtualBox. The virtualbox provider drivers are located here within the Vagrant repo: https://github.com/mitchellh/vagrant/tree/c0c7d77ea95f1b5952e9649627488081f10a082c/plugins/providers/virtualbox/driver

I couldn't find vboxmanage's 'createvm' command anywhere in the source.. I believe this is because vagrant works off 'boxes' or, images. So it most likely copies an image and then uses the import command for vboxmanage.. which is here for virtualbox 5.0.0: https://github.com/mitchellh/vagrant/blob/c0c7d77ea95f1b5952e9649627488081f10a082c/plugins/providers/virtualbox/driver/version_5_0.rb#L163

**Comment by estheban** [comment]
+1

**Comment by anthonyscolaro** [comment]
+1

**Comment by cro** [comment]
Hi folks,

All development on salt-cloud is done on the regular Salt repo at https://github.com/saltstack/salt. I'm not sure if there's a similar issue over there, but if not, you could open one.
